### ISSUE TITLE
Feature request: documentation on compiling PyTorch for Android and setting TORCHPATH

### ISSUE THREAD

**Issue by sannawag** [RuABraun/android-with-pytorch#1]
Thank you for this repo! Further documentation on compiling PyTorch for Android and setting TORCHPATH would be very helpful.

**Comment by RuABraun** [comment]
From memory `TORCHPATH` is just the file path to the torch directory. I'm not sure if it's necessary anymore.

You can find [here](https://pytorch.org/mobile/android/#building-pytorch-android-from-source) a nice guide for compiling pytorch for android. It was very easy to find with google.
